# Full directory

In [1]:
import cv2
import numpy as np
import numpy
import matplotlib.pyplot as plt
import re
import os
import sys
#%matplotlib inline

# Scratchpad

In [2]:
plt.imshow(mask)

NameError: name 'mask' is not defined

In [30]:
contours,hierachy,=cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

In [32]:
contours

[array([[[1338,  679]]], dtype=int32),
 array([[[1240,  679]]], dtype=int32),
 array([[[1178,  679]]], dtype=int32),
 array([[[1383,  678]],
 
        [[1382,  679]]], dtype=int32),
 array([[[1377,  678]]], dtype=int32),
 array([[[1358,  678]]], dtype=int32),
 array([[[1356,  678]]], dtype=int32),
 array([[[1328,  678]]], dtype=int32),
 array([[[1152,  678]],
 
        [[1152,  679]]], dtype=int32),
 array([[[1360,  677]],
 
        [[1367,  677]]], dtype=int32),
 array([[[1213,  677]],
 
        [[1213,  678]],
 
        [[1214,  679]],
 
        [[1213,  678]]], dtype=int32),
 array([[[1328,  675]],
 
        [[1328,  676]]], dtype=int32),
 array([[[1263,  675]]], dtype=int32),
 array([[[1152,  674]]], dtype=int32),
 array([[[1284,  671]]], dtype=int32),
 array([[[900, 671]]], dtype=int32),
 array([[[1280,  670]]], dtype=int32),
 array([[[896, 670]]], dtype=int32),
 array([[[1015,  669]]], dtype=int32),
 array([[[855, 669]],
 
        [[855, 670]],
 
        [[854, 671]],
 
        [

In [33]:
biggest_contour = max(contours, key = cv2.contourArea)

In [34]:
biggest_contour

array([[[1010,   80]],

       [[1008,   82]],

       [[ 831,   82]],

       [[ 830,   81]],

       [[ 831,   82]],

       [[ 829,   84]],

       [[ 827,   82]],

       [[ 828,   81]],

       [[ 827,   82]],

       [[ 826,   82]],

       [[ 826,   83]],

       [[ 825,   84]],

       [[ 825,   85]],

       [[ 823,   87]],

       [[ 640,   87]],

       [[ 639,   86]],

       [[ 638,   86]],

       [[ 638,   87]],

       [[ 639,   88]],

       [[ 639,   91]],

       [[ 638,   92]],

       [[ 636,   90]],

       [[ 637,   89]],

       [[ 636,   89]],

       [[ 635,   88]],

       [[ 635,   87]],

       [[ 633,   85]],

       [[ 633,   86]],

       [[ 632,   87]],

       [[ 632,   88]],

       [[ 632,   87]],

       [[ 633,   86]],

       [[ 634,   86]],

       [[ 635,   87]],

       [[ 635,   88]],

       [[ 636,   89]],

       [[ 635,   90]],

       [[ 464,   90]],

       [[ 463,   89]],

       [[ 463,   88]],

       [[ 463,   89]],

       [[ 462,  

In [38]:
for c in contours:
    print c

[[[1338  679]]]
[[[1240  679]]]
[[[1178  679]]]
[[[1383  678]]

 [[1382  679]]]
[[[1377  678]]]
[[[1358  678]]]
[[[1356  678]]]
[[[1328  678]]]
[[[1152  678]]

 [[1152  679]]]
[[[1360  677]]

 [[1367  677]]]
[[[1213  677]]

 [[1213  678]]

 [[1214  679]]

 [[1213  678]]]
[[[1328  675]]

 [[1328  676]]]
[[[1263  675]]]
[[[1152  674]]]
[[[1284  671]]]
[[[900 671]]]
[[[1280  670]]]
[[[896 670]]]
[[[1015  669]]]
[[[855 669]]

 [[855 670]]

 [[854 671]]

 [[855 670]]]
[[[807 669]]

 [[806 670]]

 [[807 671]]

 [[806 670]]

 [[807 669]]

 [[847 669]]]
[[[712 669]]]
[[[850 668]]

 [[849 669]]

 [[849 670]]

 [[851 670]]

 [[852 669]]

 [[853 669]]

 [[852 669]]

 [[851 670]]

 [[850 670]]

 [[849 669]]]
[[[715 668]]

 [[714 669]]

 [[714 670]]

 [[713 671]]

 [[714 670]]

 [[715 670]]

 [[716 671]]

 [[717 670]]

 [[718 671]]

 [[717 670]]

 [[716 671]]

 [[714 669]]]
[[[640 643]]]
[[[1015  612]]]
[[[1399  605]]]
[[[635 605]]

 [[634 606]]

 [[635 607]]

 [[634 608]]

 [[633 608]]

 [[633 609

In [37]:
for c in biggest_contour:
    print c
    

[[1010   80]]
[[1008   82]]
[[831  82]]
[[830  81]]
[[831  82]]
[[829  84]]
[[827  82]]
[[828  81]]
[[827  82]]
[[826  82]]
[[826  83]]
[[825  84]]
[[825  85]]
[[823  87]]
[[640  87]]
[[639  86]]
[[638  86]]
[[638  87]]
[[639  88]]
[[639  91]]
[[638  92]]
[[636  90]]
[[637  89]]
[[636  89]]
[[635  88]]
[[635  87]]
[[633  85]]
[[633  86]]
[[632  87]]
[[632  88]]
[[632  87]]
[[633  86]]
[[634  86]]
[[635  87]]
[[635  88]]
[[636  89]]
[[635  90]]
[[464  90]]
[[463  89]]
[[463  88]]
[[463  89]]
[[462  90]]
[[460  90]]
[[459  89]]
[[460  88]]
[[459  89]]
[[460  90]]
[[459  91]]
[[457  91]]
[[456  90]]
[[455  91]]
[[288  91]]
[[287  90]]
[[286  91]]
[[284  89]]
[[285  88]]
[[286  88]]
[[285  88]]
[[284  89]]
[[283  88]]
[[282  89]]
[[281  88]]
[[280  88]]
[[281  88]]
[[282  89]]
[[281  90]]
[[281  91]]
[[280  92]]
[[280  93]]
[[281  94]]
[[280  95]]
[[282  93]]
[[283  94]]
[[283 104]]
[[282 105]]
[[281 105]]
[[280 106]]
[[282 108]]
[[282 110]]
[[281 111]]
[[282 112]]
[[282 128]]
[[281 129]]


In [39]:
hull = cv2.convexHull(biggest_contour)

In [40]:
hull

array([[[1407,  173]],

       [[1406,  175]],

       [[ 457,  175]],

       [[ 280,  171]],

       [[ 280,   88]],

       [[ 828,   81]],

       [[1010,   80]],

       [[1357,   80]],

       [[1402,   82]],

       [[1406,   83]],

       [[1407,  107]]], dtype=int32)

In [23]:
image2.shape

(719, 1439, 3)

# Loop over directory

In [3]:
'''def segment_mask(image, mask):
    contours,hierachy,=cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)


    img_ =  cv2.bitwise_and(image,image,mask = mask)
    height, width = image.shape
    min_area = 100;
    images = []
    count=0
    for c in contours:
        #cv2.drawContours(img2,c,-1,(255,255,0),3)
        area = cv2.contourArea(c)

        #to remove tiny hull
        if(area > min_area):
            print(area)
            hull = cv2.convexHull(c)
            x,y,w,h = cv2.boundingRect(hull)
            print(x,y,w,h)

            temp = np.zeros((height, width, 1))
            cv2.fillPoly(temp, np.int_([hull]), (255, 255, 255))

            cropped_out = img_[y:y+h, x:x+w]
            images.append(cropped_out)
    return(images)'''

'def segment_mask(image, mask):\n    contours,hierachy,=cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)\n\n\n    img_ =  cv2.bitwise_and(image,image,mask = mask)\n    height, width = image.shape\n    min_area = 100;\n    images = []\n    count=0\n    for c in contours:\n        #cv2.drawContours(img2,c,-1,(255,255,0),3)\n        area = cv2.contourArea(c)\n\n        #to remove tiny hull\n        if(area > min_area):\n            print(area)\n            hull = cv2.convexHull(c)\n            x,y,w,h = cv2.boundingRect(hull)\n            print(x,y,w,h)\n\n            temp = np.zeros((height, width, 1))\n            cv2.fillPoly(temp, np.int_([hull]), (255, 255, 255))\n\n            cropped_out = img_[y:y+h, x:x+w]\n            images.append(cropped_out)\n    return(images)'

In [2]:
def sort_contours(cnts, reverse = False):
    # initialize the reverse flag and sort index
    i = 0
    
    # construct the list of bounding boxes and sort them from top to
    # bottom
    boundingBoxes = [cv2.boundingRect(c) for c in cnts]
    (cnts, boundingBoxes) = zip(*sorted(zip(cnts, boundingBoxes),
        key=lambda b:b[1][i], reverse=reverse))
 
    # return the list of sorted contours and bounding boxes
    return (cnts, boundingBoxes)

# Intermediate steps of image

In [27]:
def segment_mask_ordered(image, mask):
    
    
    #opening to remove small blobs 
    kernel = np.ones((1,1),np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    contours,hierachy,=cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

  
    #function calling 
    
    #check the biggest contour and pass it to a function
    biggest_contour = max(contours, key = cv2.contourArea)
    #check if the image is horizontal by checking the horizontal contour
    image2, mask2 = big_contour_check(biggest_contour, image, mask)
    #print('Type of image')
    #print(type(image2))
    #print(image2.shape)
    image = image2.copy
    mask = mask2.copy
    #plt.imshow(image)
    
    #contours,hierachy,=cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    #img_ =  cv2.bitwise_and(image,image,mask = mask)
    
    height, width = image.shape
    min_area = 400;
    images = []
    
    
    cnts, _ = sort_contours(contours)
    
    count = 1
    for c in cnts:

        area = cv2.contourArea(c)
        
        
        #to remove tiny hull
        if(area > min_area):
            print(area)
            hull = cv2.convexHull(c)
            cv2.drawContours(image_copy,[hull],-1,(255,255,0),3)
            x,y,w,h = cv2.boundingRect(hull)
            print(x,y,w,h)
            # compute the center of the contour
            M = cv2.moments(hull)
            cX = int(M["m10"] / M["m00"])
            cY = int(M["m01"] / M["m00"])

            
            cv2.putText(image_copy, str(count), (cX,cY),cv2.FONT_HERSHEY_SIMPLEX, 2, (255, 0, 0), 4)
            
            #count = count+1;
            temp = np.zeros((height, width, 1)).astype('uint8')
            cv2.fillPoly(temp, np.int_([hull]), (255, 255, 255))
            #cropped_out = img_[y:y+h, x:x+w]
            #print(temp.shape)
            
            
            cropped_out = cv2.bitwise_and(image,image,mask = temp)
            #print(cropped_out)
            #eq = cv2.equalizeHist(cropped_out)
            images.append(cropped_out)

            
    return(images,image,mask)

In [29]:
#function which checks w,h of biggest contour and rotate decider
def big_contour_check(contours2, image, mask):
    #no loop required
    hull = cv2.convexHull(contours2)
    print('Before rotation')
    print(image.shape)
    
    x,y,w,h = cv2.boundingRect(hull)
    if(w>h):
        print('Width is greater')
        out=cv2.transpose(image)
        image=cv2.flip(out,flipCode=1)
        out=cv2.transpose(mask)
        mask=cv2.flip(out,flipCode=1)
    #image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
    #images, rotate = segment_mask_ordered(image, mask)
    #mask = cv2.cvtColor(gray,cv2.COLOR_GRAY2RGB)'''
    print('Image has been rotated')
    cv2.imwrite('Rotate.jpg', image)
    return (image,mask)

        

In [7]:
print(image.shape)
print(mask.shape)

NameError: name 'image' is not defined

In [30]:
#save in test folder 
pathname1 = '/home/galactica/Sameer_Data/jupyter_notebooks/Data/IR/test/Images/'
pathname2 = '/home/galactica/Sameer_Data/jupyter_notebooks/Data/IR/test/Masks/'
#sftp://galactica@192.168.0.104/home/galactica/Galactica/External/IR_Segmentation
output_path = '/home/galactica/Sameer_Data/jupyter_notebooks/Data/IR/test/Output/'
output_path_2 = '/home/galactica/Sameer_Data/jupyter_notebooks/Data/IR/test/Output2/'
matches = 0 
count = 0
for_loop_count = 0 
for item1 in os.listdir(pathname2):    
        
            path1 = os.path.join(pathname1,item1)
            
            path2 = os.path.join(pathname2,item1)
            #read image 1 and 2
            count = count +1
            
            #read image 1 and 2
            image = cv2.imread(path1,0)
            image2 = cv2.imread(path1)
            mask = cv2.imread(path2,0)
            
            
            #step 1
            image_copy = image.copy()
            clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
            image_copy = clahe.apply(image_copy)
            #step2
            
            images, image, mask = segment_mask_ordered(image, mask)

            img_3c =  cv2.cvtColor(image,cv2.COLOR_GRAY2RGB)
            new_img = np.zeros_like(img_3c)
            panels_img = []
            
            #for loop to loop over array of images 
            for i in range (0,len(images)):
                
                
                #step3

                equalize1 = images[i]
                equalize1 = equalize1[:,:,np.newaxis]
                equalize1 = np.tile(equalize1,(1,1,3))
                #print(equalize1.shape)
                #fig, ax = plt.subplots(figsize = (20,10))
    
                #ax.imshow(images[0])
        
                cv2.imwrite(output_path + '1_Equalize' + str(i)+ '.jpg',equalize1)
        
                #step3.5
            

                im_copy = images[i].copy()
                image_copy = image.copy()

                #Sharpen
                kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])
                kernel_sobel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])

                im = cv2.filter2D(im_copy, -1, kernel)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.set_title("shapen")
                #ax.imshow(im)
                
                img_name = os.path.join(output_path,'2_Sharpen' + str(i) + '.jpg')
                #print('Path', img_name)
                cv2.imwrite(img_name,im)

                #combined shapen and original extracted
                image_combined = cv2.addWeighted(im_copy, 0.5, im, 0.5, 0)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.set_title("shapen combined with original extracted")
                #ax.imshow(image_combined)
                cv2.imwrite(output_path + '3_image_combined' + str(i)+ '.jpg',image_combined)

                im_sobel = cv2.filter2D(im_copy, -1, kernel_sobel)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.set_title("Sobel-self")
                #ax.imshow(im_sobel)
                cv2.imwrite(output_path + '4_sobelX' + str(i)+ '.jpg',im_sobel)

                kernel_dilate_2 = np.ones((3,3),np.uint8)
                dilation = cv2.dilate(im,kernel_dilate_2,iterations = 1)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.set_title("Dilation")
                #ax.imshow(dilation)
                cv2.imwrite(output_path + '5_Dilate' + str(i)+ '.jpg',dilation)
                
                kernel_erode_2 = np.ones((3,3),np.uint8)
                erosion = cv2.dilate(im,kernel_erode_2,iterations = 1)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.set_title("Erosion")
                #ax.imshow(erosion)
                cv2.imwrite(output_path + '6_Erosion' + str(i)+ '.jpg',erosion)
                
        
        
                #step 4


                scale = 1
                delta = 0
                ddepth = cv2.CV_16S  

                im = cv2.filter2D(images[i], -1, kernel)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(im)

                src = cv2.GaussianBlur(im, (3, 3), 0)

                # Gradient-x
                grad_x = cv2.Sobel(src, ddepth, 1, 0, ksize=3, scale=scale, delta=delta, borderType=cv2.BORDER_DEFAULT)

                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(grad_x)
                cv2.imwrite(output_path + '7_grad_x' + str(i)+ '.jpg',grad_x)

                # Gradient-Y
                # grad_y = cv.Scharr(gray,ddepth,0,1)
                grad_y = cv2.Sobel(src, ddepth, 0, 1, ksize=3, scale=scale, delta=delta, borderType=cv2.BORDER_DEFAULT)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(grad_y)
                cv2.imwrite(output_path + '8_grad_y' + str(i)+ '.jpg',grad_y)


                abs_grad_x = cv2.convertScaleAbs(grad_x)
                abs_grad_y = cv2.convertScaleAbs(grad_y)

                grad = cv2.addWeighted(abs_grad_x, 0.1, abs_grad_y, 0.5, 0)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(grad)
                cv2.imwrite(output_path + '9_grad_' + str(i)+ '.jpg',grad)
                
                #step 4.5 

                #Impose the binary mask on the original image
                gray = grad[:,:,np.newaxis]
                #cv2.imwrite("./test.png",gray)
                
                
                
                #step 5

                #Denoise gray
                denoised_gray = cv2.fastNlMeansDenoising(gray, None, 9, 5)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(denoised_gray)
                cv2.imwrite(output_path + '10_Denoised_gray' + str(i)+ '.jpg',denoised_gray)
                
                #step 6

                kernel_dilate_2 = np.ones((3,3),np.uint8)
                dilation = cv2.dilate(denoised_gray,kernel_dilate_2,iterations = 1)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(dilation)
                cv2.imwrite(output_path + '10_Dilation' + str(i)+ '.jpg',dilation)
                

                kernel_erode_2 = np.ones((3,3),np.uint8)
                erosion = cv2.erode(dilation,kernel_erode_2,iterations = 1)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(erosion)
                cv2.imwrite(output_path + '12_erosion' + str(i)+ '.jpg',erosion)
                
                
                #step 7 
                #Threshold the image 
                ret, thresh = cv2.threshold(erosion,
                      15, 255, cv2.THRESH_BINARY+cv2.ADAPTIVE_THRESH_MEAN_C)
                #print(thresh.shape)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(thresh)
                cv2.imwrite(output_path + '13_Thresh' + str(i)+ '.jpg',thresh)

                kernel_opening = np.ones((3,3),np.uint8)
                opening = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel_opening)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(opening)
                cv2.imwrite(output_path + '14_Opening' + str(i)+ '.jpg',opening)


                th2 = cv2.adaptiveThreshold(erosion,255,cv2.ADAPTIVE_THRESH_MEAN_C,\
                            cv2.THRESH_BINARY,63,2)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(th2)
                cv2.imwrite(output_path + '15_th2' + str(i)+ '.jpg',th2)

                th3 = cv2.adaptiveThreshold(erosion,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\
                            cv2.THRESH_BINARY,11,2)
                #fig, ax = plt.subplots(figsize = (40,10))
                #ax.imshow(th3)
                cv2.imwrite(output_path + '16_th3' + str(i)+ '.jpg',th3)
                
                
                
                #step 8 

                #erosion to remove the connecting regsions between panels 

                kernel = np.ones((1,1),np.uint8)
                erosion_2 = cv2.erode(thresh,kernel,iterations = 1)
                cv2.imwrite(output_path + '17_Erosion2' + str(i)+ '.jpg',erosion_2)
                
                #step 9 
                
                #canny for edges to be visible
                edges2= cv2.Canny(erosion_2,10,100)
                cv2.imwrite(output_path + '18_Canny' + str(i)+ '.jpg',edges2)
                
                
                #step 10 
                img_5 = edges2.copy()
                contours_image = np.expand_dims(img_5, axis=-1)
                
                
                img_7 = images[i].copy()
                img_9 = cv2.cvtColor(img_7,cv2.COLOR_GRAY2RGB)
                contours,hierachy,=cv2.findContours(erosion_2,cv2.RETR_EXTERNAL ,cv2.CHAIN_APPROX_SIMPLE)
                cv2.imwrite(output_path + str(item1) + '19_Contours_Image' + str(i)+ '.jpg',contours_image)




                count=0
                for c in contours:
                    peri = cv2.arcLength(c, True)
                    approx = cv2.approxPolyDP(c, 0.00001 * peri, True)
                    
                    #sent original image for plotting
                    
                    '''x,y,w,h = cv2.boundingRect(approx)
                    if (15 < w < 40   and 15 < h < 40):
                        cv2.rectangle(image2,(x, y), (x+w, y+h), (0, 255, 0), 2)
                        count+=1'''                        
                    #Use rotated rectangles 
                    rect = cv2.minAreaRect(approx)
                    w, h = rect[1]

                    if (5 < w < 40 and 5 < h < 40):
                        box = cv2.boxPoints(rect)
                        box = np.int0(box)
                        cv2.drawContours(image2,[box],0,(0,255,0),3)
                        
                #print(count)
                
                
            item1 = os.path.splitext(item1)[0]
            cv2.imwrite(output_path_2 + item1  + '.jpg',image2)
            
                
                
                
                
               
                


Before rotation
(719, 1439)
Width is greater
Image has been rotated


AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [12]:
w,h = image.shape

In [13]:
print(w)
print(h)

719
1439


# Improvise counting( remove big boxes)

In [0]:
            '''if(rotate==1):
                
                out=cv2.transpose(image)
                image=cv2.flip(out,flipCode=1)
                out=cv2.transpose(mask)
                mask=cv2.flip(out,flipCode=1)
                #image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
                images, rotate = segment_mask_ordered(image, mask)
                #mask = cv2.cvtColor(gray,cv2.COLOR_GRAY2RGB)'''